# modified version of the omarchy starship prompt

add_newline = false
command_timeout = 2000
format = "[$directory$git_branch$git_status]($style)$line_break$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "󰘧"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold blue"
style = "bold blue"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[git::$branch]($style) "
style = "yellow"

[git_status]
format     = '[$all_status]($style)'
style      = "red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
