theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true
mouse = false
cursorline = true
color-modes = true

[editor.lsp]
display-messages = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal]
C-s = ":update"
C-p = "file_picker"

[keys.normal."m"]
# for C development; makefile running/edits
r = ":sh make run"
k = ":sh make"
m = ":vsplit Makefile"

[keys.normal."'"]
# diff themes for whenever i feel like swapping; mainly from gruber to fuji/zed for anything that isn't code
f = ":format"
c = ":theme catppuccin_mocha"
j = ":theme fuji"
g = ":theme gruber"
z = ":theme zed_onedark"

[keys.normal.z]
q = ":write-quit-all"
