[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-duration", "2"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.niri]
input_path = '~/.config/matugen/templates/colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.quickshell]
input_path = '~/.config/matugen/templates/shell.qml'
output_path = '~/.config/quickshell/shell.qml'


#[templates.sway]
#input_path = '~/.config/matugen/templates/sway-colors.conf'
#output_path = '~/.config/sway/colors.conf'
#post_hook = 'swaymsg reload'

#[templates.kitty]
#input_path = '~/.config/matugen/templates/kitty-colors.conf'
#output_path = '~/.config/kitty/colors.conf'
#post_hook = 'pkill -SIGUSR1 kitty'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

#[templates.vicinae]
#input_path = '~/.config/matugen/templates/vicinae.toml'
#output_path = '~/.local/share/vicinae/themes/matugen.toml'
#post_hook = 'vicinae theme set matugen'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

#[templates.helix]
#input_path = '~/.config/matugen/templates/helix.toml'
#output_path = '~/.config/helix/themes/matugen.toml'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
