[display]
horizontal_padding = 3
vertical_padding = 1
width = 50
show_translation = "english"
quote_color = "blue"
translation_color = "dim"
font_size = "medium"
bold = true
border = false
source = true
modes = ["proverb", "yojijukugo", "haiku"]
seed = 6
centered = true
dynamic = false
